/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConversationMessage {
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
}
export type ExplanationLevel = bigint;
export type Language = { 'fr_FR' : null } |
  { 'tr_TR' : null } |
  { 'ar_SA' : null } |
  { 'hi_IN' : null } |
  { 'ja_JP' : null } |
  { 'en_US' : null } |
  { 'es_ES' : null } |
  { 'zh_CN' : null } |
  { 'it_IT' : null } |
  { 'pt_PT' : null } |
  { 'de_DE' : null } |
  { 'ko_KR' : null } |
  { 'ru_RU' : null };
export interface UserProfile {
  'conversationHistory' : Array<ConversationMessage>,
  'settings' : UserSettings,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'explanationLevel' : ExplanationLevel,
  'language' : Language,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearConversationHistory' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationHistory' : ActorMethod<[], Array<ConversationMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSettings' : ActorMethod<[], UserSettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveConversationMessage' : ActorMethod<[ConversationMessage], undefined>,
  'saveUserSettings' : ActorMethod<[UserSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];