/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConversationMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ExplanationLevel = IDL.Nat;
export const Language = IDL.Variant({
  'fr_FR' : IDL.Null,
  'tr_TR' : IDL.Null,
  'ar_SA' : IDL.Null,
  'hi_IN' : IDL.Null,
  'ja_JP' : IDL.Null,
  'en_US' : IDL.Null,
  'es_ES' : IDL.Null,
  'zh_CN' : IDL.Null,
  'it_IT' : IDL.Null,
  'pt_PT' : IDL.Null,
  'de_DE' : IDL.Null,
  'ko_KR' : IDL.Null,
  'ru_RU' : IDL.Null,
});
export const UserSettings = IDL.Record({
  'explanationLevel' : ExplanationLevel,
  'language' : Language,
});
export const UserProfile = IDL.Record({
  'conversationHistory' : IDL.Vec(ConversationMessage),
  'settings' : UserSettings,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearConversationHistory' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationHistory' : IDL.Func(
      [],
      [IDL.Vec(ConversationMessage)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveConversationMessage' : IDL.Func([ConversationMessage], [], []),
  'saveUserSettings' : IDL.Func([UserSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConversationMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ExplanationLevel = IDL.Nat;
  const Language = IDL.Variant({
    'fr_FR' : IDL.Null,
    'tr_TR' : IDL.Null,
    'ar_SA' : IDL.Null,
    'hi_IN' : IDL.Null,
    'ja_JP' : IDL.Null,
    'en_US' : IDL.Null,
    'es_ES' : IDL.Null,
    'zh_CN' : IDL.Null,
    'it_IT' : IDL.Null,
    'pt_PT' : IDL.Null,
    'de_DE' : IDL.Null,
    'ko_KR' : IDL.Null,
    'ru_RU' : IDL.Null,
  });
  const UserSettings = IDL.Record({
    'explanationLevel' : ExplanationLevel,
    'language' : Language,
  });
  const UserProfile = IDL.Record({
    'conversationHistory' : IDL.Vec(ConversationMessage),
    'settings' : UserSettings,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearConversationHistory' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationHistory' : IDL.Func(
        [],
        [IDL.Vec(ConversationMessage)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveConversationMessage' : IDL.Func([ConversationMessage], [], []),
    'saveUserSettings' : IDL.Func([UserSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };